export { FaWhatsapp } from "react-icons/fa"
export { FaInstagram } from "react-icons/fa6"
export { FaPhone } from "react-icons/fa6"
export { FaLocationDot } from "react-icons/fa6"
export { FaRegClock } from "react-icons/fa6"